In [22]:
import numpy as np
import mido
import tensorflow as tf

from keras.models import load_model
from mido import MidiFile, MidiTrack, Message

model = load_model('sb.h5')

In [23]:
#Midi Notes range from 0 - 127
#Input 4 notes for a chord progression
user_input = [[[27/11], [82/11], [74/11], [14/11]]]
user_input = np.array(user_input)
#reshaping input to 3D
user_input.reshape(1,1,4)

array([[[2.45454545, 7.45454545, 6.72727273, 1.27272727]]])

In [24]:
#Performing inference on the model
predict = model.predict_on_batch(user_input)

In [25]:
save = []
for i in range(16):
    save.append(predict[0][i][0])
save = np.array(save)
save = abs(save.astype(int))

In [26]:
save

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [27]:
np.save('song', save) 

In [28]:
james = np.load('song.npy',allow_pickle=True) 

In [29]:
james

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])