In [1]:
import numpy as np
import pandas as pd
import random
import tensorflow as tf

from tensorflow import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers import LSTM
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from collections import Counter

Using TensorFlow backend.


In [2]:
csv = pd.read_csv('data.csv', header = None)
data = csv.iloc[:, 0]
target = csv.iloc[:, 1]
data

0     A B A B Z
1     A C A C Z
2     A D A D Z
3     C B C B Z
4     A A A B Z
5     C C C B Z
6     A B C A Z
7     D B D B Z
8     D B A D Z
9     C A D B Z
10    D G A D Z
11    E E E F Z
12    F F A G Z
13    E B A G Z
14    B B B B Z
15    A G B E Z
16    E G B B Z
17    F F F F Z
18    A F E F Z
19    B F E G Z
Name: 0, dtype: object

In [3]:
full_lexicon = " ".join(target).split()
def create_lookup_tables(words):
    """
    Create lookup tables for vocabulary
    :param words: Input list of words
    :return: A tuple of dicts.  The first dict maps a vocab word to and integeter
             The second maps an integer back to to the vocab word
    """
    word_counts = Counter(words)
    sorted_vocab = sorted(word_counts, key=word_counts.get, reverse=True)
    int_to_vocab = {ii: word for ii, word in enumerate(sorted_vocab, 1)}
    vocab_to_int = {word: ii for ii, word in int_to_vocab.items()}

    return vocab_to_int, int_to_vocab
vocab_to_int, int_to_vocab = create_lookup_tables(full_lexicon)

In [4]:
d = []
for x in range(len(data)):
    d.append(data[x].split(" "))
for x in range(len(d)):
    for z in range(len(d[x])):
        if d[x][z] == 'A':
            d[x][z] = vocab_to_int['A']
        elif d[x][z] == 'B':
            d[x][z] = vocab_to_int['B']
        elif d[x][z] == 'C':
            d[x][z] = vocab_to_int['C']
        elif d[x][z] == 'D':
            d[x][z] = vocab_to_int['D']
        elif d[x][z] == 'E':
            d[x][z] = vocab_to_int['E']
        elif d[x][z] == 'F':
            d[x][z] = vocab_to_int['F']
        elif d[x][z] == 'G':
            d[x][z] = vocab_to_int['G']
        elif d[x][z] == 'Z':
            d[x][z] = vocab_to_int['Z']
d = [d]
d = np.array(d)
d = d.reshape(20, 1, 5) / 8

In [5]:
a = []
for x in range(len(target)):
    a.append(target[x].split(" "))
for x in range(len(a)):
    for z in range(len(a[x])):
        if a[x][z] == 'A':
            a[x][z] = int(vocab_to_int['A'])
        elif a[x][z] == 'B':
            a[x][z] = vocab_to_int['B']
        elif a[x][z] == 'C':
            a[x][z] = vocab_to_int['C']
        elif a[x][z] == 'D':
            a[x][z] = vocab_to_int['D']
        elif a[x][z] == 'E':
            a[x][z] = vocab_to_int['E']
        elif a[x][z] == 'F':
            a[x][z] = vocab_to_int['F']
        elif a[x][z] == 'G':
            a[x][z] = vocab_to_int['G']
        elif a[x][z] == 'Z':
            a[x][z] = vocab_to_int['Z']
        elif a[x][z] == '0':
            a[x][z] = 0

a = [a]
a = np.array(a)
a = a.reshape(20, 1, 10) / 8

In [6]:
d*8

array([[[2., 1., 2., 1., 4.]],

       [[2., 6., 2., 6., 4.]],

       [[2., 7., 2., 7., 4.]],

       [[6., 1., 6., 1., 4.]],

       [[2., 2., 2., 1., 4.]],

       [[6., 6., 6., 1., 4.]],

       [[2., 1., 6., 2., 4.]],

       [[7., 1., 7., 1., 4.]],

       [[7., 1., 2., 7., 4.]],

       [[6., 2., 7., 1., 4.]],

       [[7., 9., 2., 7., 4.]],

       [[8., 8., 8., 5., 4.]],

       [[5., 5., 2., 9., 4.]],

       [[8., 1., 2., 9., 4.]],

       [[1., 1., 1., 1., 4.]],

       [[2., 9., 1., 8., 4.]],

       [[8., 9., 1., 1., 4.]],

       [[5., 5., 5., 5., 4.]],

       [[2., 5., 8., 5., 4.]],

       [[1., 5., 8., 9., 4.]]])

In [7]:
a*8

array([[[2., 1., 2., 1., 1., 1., 2., 4., 0., 0.]],

       [[2., 6., 2., 6., 6., 6., 2., 4., 0., 0.]],

       [[2., 7., 2., 7., 7., 7., 2., 4., 0., 0.]],

       [[6., 1., 6., 1., 6., 1., 6., 1., 4., 0.]],

       [[2., 2., 2., 1., 2., 2., 2., 1., 4., 0.]],

       [[6., 6., 6., 1., 6., 6., 6., 1., 4., 0.]],

       [[2., 1., 6., 2., 1., 6., 2., 4., 0., 0.]],

       [[7., 1., 7., 1., 1., 1., 7., 4., 0., 0.]],

       [[7., 1., 2., 7., 1., 7., 2., 4., 0., 0.]],

       [[6., 2., 7., 1., 7., 2., 1., 7., 4., 0.]],

       [[7., 9., 2., 7., 9., 7., 2., 7., 4., 0.]],

       [[8., 8., 8., 5., 8., 8., 5., 4., 0., 0.]],

       [[5., 2., 9., 5., 2., 9., 4., 0., 0., 0.]],

       [[8., 1., 2., 9., 1., 2., 9., 4., 0., 0.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 4., 0.]],

       [[2., 9., 1., 8., 2., 2., 9., 1., 8., 4.]],

       [[8., 1., 9., 8., 1., 9., 8., 1., 1., 4.]],

       [[5., 5., 5., 5., 5., 5., 5., 5., 4., 0.]],

       [[2., 5., 8., 5., 2., 5., 8., 5., 4., 0.]],

       [[1.,

In [8]:
#splitting data into train and test sets. 3/4 train, 1/4 test.
x_train,x_test,y_train,y_test = train_test_split(d, a, test_size=0.2, shuffle=False, random_state=42)

In [9]:
#getting the right tensor shape for this was a BITCH
model = Sequential()  
model.add(LSTM(128, input_shape=(1, 5),return_sequences=True, activation = 'relu'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(LSTM(128, return_sequences=True, activation = 'tanh'))
model.add(Dropout(0.2))
model.add(Dense(units=10))
model.add(Dense(units=10))
model.add(Dense(units=10))
model.add(Activation('softmax'))



model.compile(loss='mean_absolute_error', optimizer='adam')
print(model.summary())

W0916 03:04:29.716599  7780 deprecation_wrapper.py:119] From D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0916 03:04:29.726572  7780 deprecation_wrapper.py:119] From D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0916 03:04:29.728567  7780 deprecation_wrapper.py:119] From D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0916 03:04:30.630054  7780 deprecation_wrapper.py:119] From D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0916 03:04:30.635040  7780 deprecation.py:506] From D:\Anaconda\lib\site-packages\keras\backend\t

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 1, 128)            68608     
_________________________________________________________________
lstm_2 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
lstm_3 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
lstm_4 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
lstm_5 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
lstm_6 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
lstm_7 (LSTM)                (None, 1, 128)           

In [17]:
model.fit(d, a, epochs=25, batch_size=5, verbose=2,validation_data=(x_test, y_test))

Train on 20 samples, validate on 4 samples
Epoch 1/25
 - 0s - loss: 0.3585 - val_loss: 0.4925
Epoch 2/25
 - 0s - loss: 0.3580 - val_loss: 0.4925
Epoch 3/25
 - 0s - loss: 0.3578 - val_loss: 0.4925
Epoch 4/25
 - 0s - loss: 0.3580 - val_loss: 0.4925
Epoch 5/25
 - 0s - loss: 0.3576 - val_loss: 0.4922
Epoch 6/25
 - 0s - loss: 0.3574 - val_loss: 0.4925
Epoch 7/25
 - 0s - loss: 0.3576 - val_loss: 0.4922
Epoch 8/25
 - 0s - loss: 0.3577 - val_loss: 0.4929
Epoch 9/25
 - 0s - loss: 0.3574 - val_loss: 0.4928
Epoch 10/25
 - 0s - loss: 0.3574 - val_loss: 0.4925
Epoch 11/25
 - 0s - loss: 0.3569 - val_loss: 0.4925
Epoch 12/25
 - 0s - loss: 0.3573 - val_loss: 0.4925
Epoch 13/25
 - 0s - loss: 0.3572 - val_loss: 0.4921
Epoch 14/25
 - 0s - loss: 0.3570 - val_loss: 0.4920
Epoch 15/25
 - 0s - loss: 0.3568 - val_loss: 0.4921
Epoch 16/25
 - 0s - loss: 0.3571 - val_loss: 0.4917
Epoch 17/25
 - 0s - loss: 0.3568 - val_loss: 0.4914
Epoch 18/25
 - 0s - loss: 0.3567 - val_loss: 0.4915
Epoch 19/25
 - 0s - loss: 0.35

In [11]:
guess = np.array([2, 1, 1, 1, 4])
guess = guess.reshape(1,1,5)

In [12]:
predict = model.predict_on_batch(guess)*8

In [13]:
array = np.around(predict[0][0])
print(array)
new = []

[2. 1. 0. 1. 1. 1. 1. 1. 0. 0.]


In [14]:
for z in range(len(array)):
    if array[z] == 1:
        new.append(int_to_vocab[1])
    elif array[z] == 2:
        new.append(int_to_vocab[2])
    elif array[z] == 3:
        new.append(int_to_vocab[3])
    elif array[z] == 4:
        new.append(int_to_vocab[4])
    elif array[z] == 5:
        new.append(int_to_vocab[5])
    elif array[z] == 6:
        new.append(int_to_vocab[6])
    elif array[z] == 7:
        new.append(int_to_vocab[7])
    elif array[z] == 8:
        new.append(int_to_vocab[8])
    elif array[z] == 0:
        new.append(0)

In [15]:
new

['A', 'B', 0, 'B', 'B', 'B', 'B', 'B', 0, 0]

In [16]:
from keras.models import load_model

# Creates a HDF5 file 'my_model.h5'
model.save('my_model.h5')