In [10]:
import numpy as np
import random

from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers import LSTM
from sklearn.model_selection import train_test_split

In [11]:
#random int between 1 and 8. 4 ints in each array. 1000 arrays.
data = [[random.randint(1,8) for j in range(4)] for i in range(1000)]
data = np.array(data, dtype=float)
#random int between 1 and 8. 16 ints in each array. 1000 arrays.
target = [[random.randint(1,8) for j in range(16)] for i in range(1000)]
target = np.array(target, dtype=float)

In [12]:
#reshaping data into correct sized tensors. Then normalizing values. A,B,C,D,E,F,G,<EOS> so 8 characters in vocabulary
data = data.reshape((1000, 1, 4))/8 
target = target.reshape((1000, 1, 16))/8 

In [13]:
data*8

array([[[1., 5., 4., 4.]],

       [[8., 3., 6., 5.]],

       [[5., 6., 6., 6.]],

       ...,

       [[3., 7., 6., 6.]],

       [[7., 4., 6., 4.]],

       [[6., 8., 8., 8.]]])

In [14]:
target*8

array([[[7., 8., 3., ..., 1., 4., 7.]],

       [[8., 7., 4., ..., 5., 7., 3.]],

       [[4., 6., 7., ..., 3., 1., 1.]],

       ...,

       [[6., 2., 5., ..., 3., 8., 1.]],

       [[3., 6., 7., ..., 1., 5., 6.]],

       [[5., 1., 7., ..., 7., 5., 5.]]])

In [15]:
#splitting data into train and test sets. 3/4 train, 1/4 test.
x_train,x_test,y_train,y_test = train_test_split(data, target, test_size=0.25, shuffle=False, random_state=42)

In [16]:
#getting the right tensor shape for this was a BITCH
model = Sequential()  
model.add(LSTM(128, input_shape=(1, 4),return_sequences=True, activation = 'relu'))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units=128))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units=128))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dense(units=16))
model.add(Activation('tanh'))



model.compile(loss='mean_absolute_error', optimizer='adam')
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 1, 128)            68096     
_________________________________________________________________
lstm_6 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
dropout_3 (Dropout)          (None, 1, 128)            0         
_________________________________________________________________
dense_4 (Dense)              (None, 1, 128)            16512     
_________________________________________________________________
lstm_7 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
dropout_4 (Dropout)          (None, 1, 128)            0         
_________________________________________________________________
dense_5 (Dense)              (None, 1, 128)           

In [17]:
model.fit(data, target, nb_epoch=100, batch_size=200, verbose=2,validation_data=(x_test, y_test))

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 1000 samples, validate on 250 samples
Epoch 1/100
 - 2s - loss: 0.5604 - val_loss: 0.5563
Epoch 2/100
 - 0s - loss: 0.5481 - val_loss: 0.5395
Epoch 3/100
 - 0s - loss: 0.5259 - val_loss: 0.5060
Epoch 4/100
 - 0s - loss: 0.4790 - val_loss: 0.4335
Epoch 5/100
 - 0s - loss: 0.3848 - val_loss: 0.3054
Epoch 6/100
 - 0s - loss: 0.2777 - val_loss: 0.2828
Epoch 7/100
 - 0s - loss: 0.2891 - val_loss: 0.2706
Epoch 8/100
 - 0s - loss: 0.2592 - val_loss: 0.2531
Epoch 9/100
 - 0s - loss: 0.2585 - val_loss: 0.2590
Epoch 10/100
 - 0s - loss: 0.2554 - val_loss: 0.2495
Epoch 11/100
 - 0s - loss: 0.2510 - val_loss: 0.2506
Epoch 12/100
 - 0s - loss: 0.2522 - val_loss: 0.2496
Epoch 13/100
 - 0s - loss: 0.2507 - val_loss: 0.2498
Epoch 14/100
 - 0s - loss: 0.2506 - val_loss: 0.2498
Epoch 15/100
 - 0s - loss: 0.2506 - val_loss: 0.2498
Epoch 16/100
 - 0s - loss: 0.2502 - val_loss: 0.2494
Epoch 17/100
 - 0s - loss: 0.2501 - val_loss: 0.2491
Epoch 18/100
 - 0s - loss: 0.2501 - val_loss: 0.2490
Epoch 19

In [20]:
model.predict(data)*8

array([[[4.7695127, 4.6966414, 4.840691 , ..., 4.780595 , 4.166058 ,
         4.386244 ]],

       [[4.888697 , 4.819085 , 4.9599524, ..., 4.8992205, 4.278331 ,
         4.5040503]],

       [[4.7964416, 4.7241616, 4.867595 , ..., 4.807404 , 4.191208 ,
         4.4127154]],

       ...,

       [[4.772891 , 4.7      , 4.8440366, ..., 4.783985 , 4.1691046,
         4.3895125]],

       [[4.8779297, 4.808011 , 4.9491687, ..., 4.8885   , 4.2681327,
         4.4933643]],

       [[4.8122654, 4.740395 , 4.8834205, ..., 4.8231015, 4.205991 ,
         4.4282575]]], dtype=float32)