In [29]:
import numpy as np
import random

from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers import LSTM
from sklearn.model_selection import train_test_split

In [30]:
#random int between 1 and 8. 4 ints in each array. 1000 arrays.
data = [[random.randint(1,8) for j in range(4)] for i in range(1000)]
data = np.array(data, dtype=float)
#random int between 1 and 8. 16 ints in each array. 1000 arrays.
target = [[random.randint(1,8) for j in range(16)] for i in range(1000)]
target = np.array(target, dtype=float)

In [31]:
#reshaping data into correct sized tensors. Then normalizing values. A,B,C,D,E,F,G,<EOS> so 8 characters in vocabulary
data = data.reshape((1000, 1, 4))/8 
target = target.reshape((1000, 1, 16))/8 

In [32]:
data*8

array([[[5., 8., 6., 1.]],

       [[1., 5., 4., 4.]],

       [[3., 6., 3., 1.]],

       ...,

       [[5., 5., 7., 7.]],

       [[7., 2., 4., 3.]],

       [[3., 5., 1., 2.]]])

In [33]:
target*8

array([[[6., 8., 8., ..., 7., 5., 6.]],

       [[6., 4., 3., ..., 1., 5., 4.]],

       [[5., 7., 8., ..., 8., 1., 3.]],

       ...,

       [[3., 7., 8., ..., 3., 8., 6.]],

       [[8., 2., 3., ..., 2., 4., 7.]],

       [[6., 8., 2., ..., 7., 4., 1.]]])

In [34]:
#splitting data into train and test sets. 3/4 train, 1/4 test.
x_train,x_test,y_train,y_test = train_test_split(data, target, test_size=0.25, shuffle=False, random_state=42)

In [35]:
#getting the right tensor shape for this was a BITCH
model = Sequential()  
model.add(LSTM(128, input_shape=(1, 4),return_sequences=True, activation = 'relu'))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units=128))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units=128))
model.add(LSTM(128, return_sequences=True, activation = 'relu'))
model.add(Dense(units=16))
model.add(Activation('tanh'))



model.compile(loss='mean_absolute_error', optimizer='adam')
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_13 (LSTM)               (None, 1, 128)            68096     
_________________________________________________________________
lstm_14 (LSTM)               (None, 1, 128)            131584    
_________________________________________________________________
dropout_7 (Dropout)          (None, 1, 128)            0         
_________________________________________________________________
dense_10 (Dense)             (None, 1, 128)            16512     
_________________________________________________________________
lstm_15 (LSTM)               (None, 1, 128)            131584    
_________________________________________________________________
dropout_8 (Dropout)          (None, 1, 128)            0         
_________________________________________________________________
dense_11 (Dense)             (None, 1, 128)           

In [36]:
model.fit(data, target, nb_epoch=100, batch_size=200, verbose=2,validation_data=(x_test, y_test))

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 1000 samples, validate on 250 samples
Epoch 1/100
 - 3s - loss: 0.5589 - val_loss: 0.5568
Epoch 2/100
 - 0s - loss: 0.5455 - val_loss: 0.5378
Epoch 3/100
 - 0s - loss: 0.5195 - val_loss: 0.4970
Epoch 4/100
 - 0s - loss: 0.4609 - val_loss: 0.4048
Epoch 5/100
 - 0s - loss: 0.3442 - val_loss: 0.2669
Epoch 6/100
 - 0s - loss: 0.2740 - val_loss: 0.2917
Epoch 7/100
 - 0s - loss: 0.2783 - val_loss: 0.2511
Epoch 8/100
 - 0s - loss: 0.2525 - val_loss: 0.2596
Epoch 9/100
 - 0s - loss: 0.2577 - val_loss: 0.2519
Epoch 10/100
 - 0s - loss: 0.2499 - val_loss: 0.2485
Epoch 11/100
 - 0s - loss: 0.2506 - val_loss: 0.2489
Epoch 12/100
 - 0s - loss: 0.2494 - val_loss: 0.2481
Epoch 13/100
 - 0s - loss: 0.2483 - val_loss: 0.2485
Epoch 14/100
 - 0s - loss: 0.2485 - val_loss: 0.2483
Epoch 15/100
 - 0s - loss: 0.2482 - val_loss: 0.2482
Epoch 16/100
 - 0s - loss: 0.2480 - val_loss: 0.2482
Epoch 17/100
 - 0s - loss: 0.2484 - val_loss: 0.2480
Epoch 18/100
 - 0s - loss: 0.2482 - val_loss: 0.2480
Epoch 19

In [40]:
guess = np.array([1, 2, 3, 4])
guess = guess.reshape(1,1,4)

In [42]:
model.predict_on_batch(guess)*8

array([[[4.578665 , 4.606306 , 5.302658 , 4.667034 , 4.672136 ,
         4.57725  , 4.51742  , 4.573648 , 4.38261  , 5.2194486,
         4.61569  , 4.71391  , 5.2831087, 5.2301826, 5.2145734,
         5.3287463]]], dtype=float32)